from fastapi import FastAPI, HTTPException, Header, Query, Depends
from fastapi.middleware.cors import CORSMiddleware
from datetime import datetime 
from pydantic import BaseModel, Field
from typing import Optional, Literal

#CONFIGURATION
API_KEY = 'arceo-api-key-123'
API_VERSION = '1.0'

#Pydantic Schema
class Character(BaseModel):
    id: int
    game: Literal["League of Legends", "Dota 2", "Mobile Legends", "Arena of Valor"]
    name: str = Field(min_length=1)
    title: str = Field(min_length=1)
    region: str = Field(min_length=1)
    race: str = Field(min_length=1)
    faction: str = Field(min_length=1)
    origin: str = Field(min_length=1)
    personality: str = Field(min_length=1)
    relationships: str = Field(min_length=1)
    enemies: str = Field(min_length=1)
    allies: str = Field(min_length=1)
    major_events: str = Field(min_length=1)
    current_status: str = Field(min_length=1)
    lore: Optional[str] = None
    image: Optional[str] = None
    role: str = Field(min_length=1)
    weapon: str = Field(min_length=1)
    difficulty: Literal["Easy", "Medium", "Hard"]
    skill_floor: Literal[1, 2, 3, 4, 5]
    skill_ceiling: Literal[1, 2, 3, 4, 5]
    playstyle: Literal["Burst", "Sustained", "Poke", "Frontline", "Ambush", "Utility"]
    mobility: Literal["Low", "Medium", "High"]
    survivability: Literal["Squishy", "Sturdy", "Sustain-heavy"]
    mechanical_demand: Literal["Aimed Skillshots", "Point-and-Click", "Auto-Attack Based"]
    kit_complexity: Literal["Low", "Medium", "High"]
    power_curve: Literal["Early", "Even", "Late"]
    snowball_dependence: Literal["Needs a Lead", "Neutral", "Can Play From Behind"]
    team_dependence: Literal["Self-Sufficient", "Balanced", "Team-Reliant"]
    year_released: int = Field(ge=1998, le=2150)
    attack_type: Literal["Melee", "Ranged"]
    damage_type: Literal["AD", "AP"]
    damage_source: Literal["Abilities", "Auto-Attacks"]



app = FastAPI(
    title="Simple MOBA character, skins, and lore API",
    description="A beginner-friendly REST API containing information about MOBA characters, skins, and lore.",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

characters = [
    {
        "id": 1,
        "game": "League of Legends",
        "name": "Aatrox",
        "title": "The Darkin Blade",
        "region": "Shurima",
        "race": "Darkin / Ascended",
        "faction": "Darkin",
        "origin": "Ancient Shurima",
        "personality": "Proud, wrathful, violent, nihilistic, and resentful.",
        "relationships": "Formerly allied with the Ascended and other Darkin.",
        "enemies": "Zoe, Xolaani, Kayle, and the mortal world.",
        "allies": "Other Darkin and formerly the Ascended Host.",
        "major_events": "Ascension in Shurima, war against the Void, the Great Darkin War, imprisonment within the Darkin Blade, and possession of mortal hosts.",
        "current_status": "Active and seeking an apocalyptic end to his existence.",
        "lore": "Aatrox was once one of Shurima's greatest Ascended warriors, fighting alongside the empire against the Void and becoming a legendary champion of its people. After Shurima's fall, however, the Ascended known as the Darkin turned against one another and waged a devastating war. Aatrox was eventually imprisoned within his own weapon, leaving his consciousness trapped within the Darkin Blade. Through possessing mortal hosts, he can once again take physical form, but every host is temporary and imperfect. Now consumed by hatred and despair, Aatrox seeks to destroy the world around him, believing that only an end to existence can finally free him from his cursed existence.",
        "image": "aatrox.jpg",
        "role": "Fighter",
        "playstyle": "Sustained",
        "mobility": "Medium",
        "survivability": "Sustain-heavy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Neutral",
        "team_dependence": "Self-Sufficient",
        "weapon": "Darkin Blade",
        "difficulty": "Medium",
        "skill_floor": 3,
        "skill_ceiling": 4,
        "year_released": 2013,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Abilities"
    },
    {
        "id": 2,
        "game": "League of Legends",
        "name": "Zed",
        "title": "The Master of Shadows",
        "region": "Ionia",
        "race": "Human",
        "faction": "Order of Shadow",
        "origin": "Ionia",
        "personality": "Ruthless, pragmatic, ambitious, disciplined, and fiercely protective of Ionia.",
        "relationships": "Former student of Kusho and brother-like rival of Shen.",
        "enemies": "Shen, the Kinkou Order, Noxus, and Jhin.",
        "allies": "The Order of Shadow.",
        "major_events": "Training under Kusho, discovering shadow magic, leaving the Kinkou, creating the Order of Shadow, and resisting Noxus.",
        "current_status": "Leader of the Order of Shadow and an influential defender of Ionia.",
        "lore": "Zed was raised within the Kinkou Order under the guidance of its leader, Kusho, alongside Shen. Although he initially followed the Kinkou's teachings, Zed became frustrated by their refusal to use lethal force against threats to Ionia. His search for greater power eventually led him to forbidden shadow magic. Zed ultimately broke away from the Kinkou and established the Order of Shadow, training warriors who embraced more ruthless methods. Though considered a criminal by the Kinkou, Zed believes that his actions are necessary to protect Ionia from its enemies. His rivalry with Shen remains deeply personal, shaped by their shared history and opposing philosophies.",
        "image": "zed.jpg",
        "role": "Assassin",
        "playstyle": "Ambush",
        "mobility": "High",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "High",
        "power_curve": "Early",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Self-Sufficient",
        "weapon": "Shuriken and Shadow Magic",
        "difficulty": "Hard",
        "skill_floor": 4,
        "skill_ceiling": 5,
        "year_released": 2012,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Abilities"
    },
    {
        "id": 3,
        "game": "League of Legends",
        "name": "Akali",
        "title": "The Rogue Assassin",
        "region": "Ionia",
        "race": "Human",
        "faction": "Independent / Former Kinkou",
        "origin": "Navori, Ionia",
        "personality": "Independent, determined, impulsive, rebellious, and protective.",
        "relationships": "Former student of Shen and Kennen and former member of the Kinkou Order.",
        "enemies": "Noxian invaders, the Order of Shadow, and threats to Ionia.",
        "allies": "Shen, Kennen, and former Kinkou members.",
        "major_events": "Kinkou training, the Noxian invasion, Zed's coup, and her departure from the Kinkou Order.",
        "current_status": "An independent assassin defending Ionia.",
        "lore": "Akali was trained from a young age by the Kinkou Order, learning the art of assassination under Shen and Kennen. As Noxus invaded Ionia, she became increasingly dissatisfied with the Kinkou's methods and their hesitation to directly confront threats. Eventually, Akali abandoned the organization and chose to fight on her own terms. She continues to defend Ionia as a rogue assassin, relying on her speed, skill, and determination rather than the authority of an organization. Although she still respects those who trained her, Akali has made it clear that her path belongs to her alone.",
        "image": "akali.jpg",
        "role": "Assassin",
        "playstyle": "Ambush",
        "mobility": "High",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "High",
        "power_curve": "Even",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Self-Sufficient",
        "weapon": "Kunai and Kama",
        "difficulty": "Hard",
        "skill_floor": 4,
        "skill_ceiling": 5,
        "year_released": 2010,
        "attack_type": "Melee",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 4,
        "game": "League of Legends",
        "name": "Syndra",
        "title": "The Dark Sovereign",
        "region": "Ionia",
        "race": "Human",
        "faction": "Independent",
        "origin": "Ionia",
        "personality": "Proud, fiercely independent, rebellious, distrustful, and obsessed with freedom.",
        "relationships": "Formerly connected to Ionian elders and a mentor who attempted to suppress her power.",
        "enemies": "Those who attempt to control or suppress her.",
        "allies": "Primarily herself.",
        "major_events": "Manifestation of her magic, suppression by her mentor, imprisonment, escape, and emergence as the Dark Sovereign.",
        "current_status": "Free and wielding immense magical power.",
        "lore": "Syndra was born with extraordinary magical power, but those around her feared what she might become. Her mentor attempted to suppress her abilities, teaching her that her strength was dangerous and needed to be controlled. Eventually, Syndra was imprisoned and her power was deliberately restrained. When she finally broke free, the years of suppression transformed her desire for freedom into an intense hatred of anyone who might attempt to control her again. Syndra now commands immense telekinetic power and lives independently, determined to ensure that no one will ever take away her freedom again.",
        "image": "syndra.jpg",
        "role": "Mage",
        "playstyle": "Burst",
        "mobility": "Low",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Medium",
        "power_curve": "Late",
        "snowball_dependence": "Neutral",
        "team_dependence": "Balanced",
        "weapon": "Dark Spheres",
        "difficulty": "Hard",
        "skill_floor": 4,
        "skill_ceiling": 4,
        "year_released": 2012,
        "attack_type": "Ranged",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 5,
        "game": "League of Legends",
        "name": "Mordekaiser",
        "title": "The Iron Revenant",
        "region": "Noxus",
        "race": "Revenant / Undead",
        "faction": "Mordekaiser's Forces",
        "origin": "Ancient Noxian lands",
        "personality": "Tyrannical, calculating, proud, cruel, patient, and obsessed with domination.",
        "relationships": "Historically connected to his mortal armies and necromancers.",
        "enemies": "Noxus, living civilizations, and those who oppose his resurrection.",
        "allies": "Undead followers and those enslaved by his necromantic power.",
        "major_events": "Life as Sahn-Uzal, death, discovery of the afterlife, return to Runeterra, creation of an undead empire, defeat, and banishment.",
        "current_status": "Preparing to return and establish dominion over the living and dead.",
        "lore": "Once known as Sahn-Uzal, Mordekaiser was a ruthless warlord who conquered vast territories during his mortal life. After his death, he discovered that the afterlife was not the glorious realm he had expected. Refusing to accept his fate, he used necromantic knowledge to return to the mortal world in an enormous suit of armor. Mordekaiser eventually established an empire built upon the dead, enslaving souls and seeking knowledge that would allow him to conquer both life and death itself. Though his enemies have defeated and banished him before, Mordekaiser has never truly been destroyed. His ultimate goal remains the creation of an eternal empire under his absolute rule.",
        "image": "mordekaiser.jpg",
        "role": "Fighter",
        "playstyle": "Sustained",
        "mobility": "Low",
        "survivability": "Sturdy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Low",
        "power_curve": "Late",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Self-Sufficient",
        "weapon": "Mace",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 3,
        "year_released": 2010,
        "attack_type": "Melee",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 6,
        "game": "League of Legends",
        "name": "Zoe",
        "title": "The Aspect of Twilight",
        "region": "Targon",
        "race": "Human Host / Celestial Aspect",
        "faction": "Aspects of Targon",
        "origin": "Mount Targon",
        "personality": "Playful, mischievous, curious, carefree, unpredictable, and dangerously powerful.",
        "relationships": "Connected to the celestial Aspects and opposed by Aatrox.",
        "enemies": "Aatrox and beings opposed to the Aspects.",
        "allies": "The celestial powers of Targon.",
        "major_events": "Becoming the Aspect of Twilight and serving as a messenger for cosmic events.",
        "current_status": "Active as the Aspect of Twilight.",
        "lore": "Zoe was once an ordinary young girl who lived on Mount Targon, but her extraordinary curiosity eventually brought her to the attention of the celestial Aspect of Twilight. After becoming its host, Zoe gained immense cosmic power and ceased aging like an ordinary human. She travels across Runeterra with a playful and seemingly carefree attitude, often treating cosmic events as games. Despite her childish behavior, Zoe possesses tremendous power and can alter reality in ways that ordinary mortals cannot comprehend. As the Aspect of Twilight, she serves as a messenger between the celestial realm and the mortal world.",
        "image": "zoe.jpg",
        "role": "Mage",
        "playstyle": "Poke",
        "mobility": "Medium",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Neutral",
        "team_dependence": "Balanced",
        "weapon": "Celestial Magic",
        "difficulty": "Hard",
        "skill_floor": 4,
        "skill_ceiling": 5,
        "year_released": 2017,
        "attack_type": "Ranged",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 7,
        "game": "League of Legends",
        "name": "Pantheon",
        "title": "The Unbreakable Spear",
        "region": "Targon",
        "race": "Human",
        "faction": "Rakkor",
        "origin": "Mount Targon",
        "personality": "Stubborn, courageous, defiant, determined, compassionate, and protective.",
        "relationships": "Former host of the Aspect of War and enemy of Aatrox.",
        "enemies": "Aatrox, hostile celestial beings, and threats to mortals.",
        "allies": "Rakkor warriors and mortal defenders.",
        "major_events": "Training as a Rakkor warrior, becoming host to the Aspect of War, surviving Aatrox's attack, and rejecting celestial authority.",
        "current_status": "Active as Atreus, fighting for mortals through his own strength.",
        "lore": "Atreus was a Rakkor warrior who climbed Mount Targon and became the host of the celestial Aspect of War. Although the Aspect granted him incredible power, Atreus eventually discovered that celestial beings did not value mortal lives in the same way he did. During a confrontation with Aatrox, the Aspect of War was destroyed and Atreus was left seemingly dead. Against all odds, he survived through sheer determination. Refusing to surrender his identity to the celestial powers, Atreus now fights as Pantheon by his own will. He represents the strength of ordinary mortals who refuse to be controlled by gods or cosmic forces.",
        "image": "pantheon.jpg",
        "role": "Fighter",
        "playstyle": "Burst",
        "mobility": "High",
        "survivability": "Sturdy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Low",
        "power_curve": "Early",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Balanced",
        "weapon": "Spear and Shield",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 3,
        "year_released": 2010,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Abilities"
    },
    {
        "id": 8,
        "game": "League of Legends",
        "name": "Kha'Zix",
        "title": "The Voidreaver",
        "region": "The Void",
        "race": "Voidborn",
        "faction": "The Void",
        "origin": "The Void",
        "personality": "Predatory, intelligent, patient, adaptive, and obsessed with hunting.",
        "relationships": "Has a major rivalry with Rengar.",
        "enemies": "Rengar and powerful creatures that threaten it.",
        "allies": "Other Void creatures, although Kha'Zix primarily acts independently.",
        "major_events": "Emergence from the Void, hunting across Runeterra, evolution through consumption, and rivalry with Rengar.",
        "current_status": "Active Voidborn predator continually evolving through hunting.",
        "lore": "Kha'Zix is a Voidborn predator that emerged into Runeterra with a single instinct: hunt and evolve. It stalks powerful creatures, consuming them and adapting its body to become an increasingly dangerous hunter. Kha'Zix's intelligence allows it to recognize weaknesses and change its physical form to overcome new challenges. Its most famous rivalry is with Rengar, a hunter who has dedicated himself to finding and killing increasingly powerful prey. To Kha'Zix, however, their conflict is more than a simple hunt—it is an opportunity to evolve by defeating one of Runeterra's greatest predators.",
        "image": "khazix.jpg",
        "role": "Assassin",
        "playstyle": "Ambush",
        "mobility": "High",
        "survivability": "Squishy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Medium",
        "power_curve": "Early",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Self-Sufficient",
        "weapon": "Claws",
        "difficulty": "Medium",
        "skill_floor": 3,
        "skill_ceiling": 4,
        "year_released": 2012,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Abilities"
    },
    {
        "id": 9,
        "game": "League of Legends",
        "name": "Malzahar",
        "title": "The Prophet of the Void",
        "region": "Shurima",
        "race": "Human / Void-Touched",
        "faction": "The Void",
        "origin": "Icathia / Shurima",
        "personality": "Fanatical, prophetic, detached, manipulative, and convinced of the Void's destiny.",
        "relationships": "Closely connected to the Void and its creatures.",
        "enemies": "Kai'Sa, Shuriman defenders, and forces opposing the Void.",
        "allies": "Voidborn creatures.",
        "major_events": "Development of prophetic visions, exposure to the Void, transformation into its prophet, and spreading Void influence.",
        "current_status": "Active servant and prophet of the Void.",
        "lore": "Malzahar was once a wandering seer who possessed visions of events yet to come. His search for meaning eventually led him toward the ancient ruins of Icathia, where he encountered the overwhelming presence of the Void. The experience transformed him, granting him visions of a future in which the Void consumes Runeterra. Rather than resisting its influence, Malzahar embraced what he believed to be his destiny and became its prophet. He now travels across Shurima spreading the Void's influence and summoning its creatures, convinced that the destruction of the world is not an evil but an inevitable transformation.",
        "image": "malzahar.jpg",
        "role": "Mage",
        "playstyle": "Sustained",
        "mobility": "Low",
        "survivability": "Squishy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Low",
        "power_curve": "Even",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Balanced",
        "weapon": "Void Magic",
        "difficulty": "Easy",
        "skill_floor": 1,
        "skill_ceiling": 2,
        "year_released": 2010,
        "attack_type": "Ranged",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 10,
        "game": "League of Legends",
        "name": "Viego",
        "title": "The Ruined King",
        "region": "Camavor / Shadow Isles",
        "race": "Human / Wraith",
        "faction": "Camavor / Ruined Forces",
        "origin": "Camavor",
        "personality": "Obsessive, possessive, arrogant, emotionally unstable, and consumed by grief.",
        "relationships": "Husband of Isolde and connected to Kalista, Hecarim, Gwen, Senna, and Lucian.",
        "enemies": "Lucian, Senna, Gwen, and the Sentinels of Light.",
        "allies": "Hecarim, Thresh, the Black Mist, and corrupted followers.",
        "major_events": "Marriage to Isolde, Isolde's death, attempted resurrection, the Ruination, and the spread of the Black Mist.",
        "current_status": "The Ruined King and a major supernatural threat to Runeterra.",
        "lore": "Viego was once a young king of Camavor whose greatest obsession was his wife, Isolde. When she died after being poisoned, Viego became consumed by grief and refused to accept her death. His attempt to restore Isolde using the waters of the Blessed Isles caused a catastrophic magical event known as the Ruination. The islands were corrupted and transformed into the Shadow Isles, while Viego himself became a wraith surrounded by the Black Mist. Centuries later, he returned to Runeterra and attempted to reunite with Isolde by force, spreading the Black Mist across the world. His obsession with recovering his lost love has made him one of Runeterra's greatest supernatural threats.",
        "image": "viego.jpg",
        "role": "Fighter / Assassin",
        "playstyle": "Ambush",
        "mobility": "Medium",
        "survivability": "Sturdy",
        "mechanical_demand": "Auto-Attack Based",
        "kit_complexity": "High",
        "power_curve": "Even",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Self-Sufficient",
        "weapon": "Ruined Blade",
        "difficulty": "Medium",
        "skill_floor": 3,
        "skill_ceiling": 5,
        "year_released": 2021,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 11,
        "game": "League of Legends",
        "name": "Jhin",
        "title": "The Virtuoso",
        "region": "Ionia",
        "race": "Human",
        "faction": "Independent",
        "origin": "Ionia",
        "personality": "Obsessive, theatrical, meticulous, narcissistic, artistic, and disturbed.",
        "relationships": "Connected to Zed, Shen, Akali, and the Kinkou through his history as the Golden Demon.",
        "enemies": "Zed, Shen, and the Kinkou Order.",
        "allies": "Occasional employers and individuals who assist his artistic ambitions.",
        "major_events": "Murders in Ionia, imprisonment by the Kinkou, release through Noxian manipulation, and return to his killings.",
        "current_status": "Active and pursuing his vision of murder as art.",
        "lore": "Jhin is a meticulous and theatrical murderer who believes killing is a form of art. Once known as the Golden Demon, he terrorized Ionia before being captured and imprisoned by the Kinkou. He was eventually released through the schemes of Noxian forces and returned to his deadly performances, treating every murder as part of a carefully constructed masterpiece.",
        "image": "jihn.jpg",
        "role": "Marksman",
        "playstyle": "Poke",
        "mobility": "Low",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Neutral",
        "team_dependence": "Team-Reliant",
        "weapon": "Whisper",
        "difficulty": "Hard",
        "skill_floor": 3,
        "skill_ceiling": 4,
        "year_released": 2016,
        "attack_type": "Ranged",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 12,
        "game": "League of Legends",
        "name": "Ziggs",
        "title": "The Hexplosives Expert",
        "region": "Piltover / Zaun",
        "race": "Yordle",
        "faction": "Independent",
        "origin": "Bandle City",
        "personality": "Energetic, chaotic, curious, reckless, enthusiastic, and obsessed with explosions.",
        "relationships": "Close friend of Jinx and associated with Piltover's scientific community.",
        "enemies": "Piltover authorities and anyone restricting his experiments.",
        "allies": "Jinx and various Zaunites.",
        "major_events": "Leaving Bandle City, traveling to Piltover, developing explosives, moving toward Zaun, and meeting Jinx.",
        "current_status": "Active in Zaun and continuing his explosive experiments.",
        "lore": "Ziggs is a brilliant and eccentric yordle fascinated by explosives and scientific experimentation. Originally from Bandle City, he traveled to Piltover and became fascinated with its technology. Eventually finding a kindred spirit in Jinx, he settled in Zaun, where he could freely pursue increasingly dangerous experiments without worrying about conventional rules or safety.",
        "image": "ziggs.jpg",
        "role": "Mage",
        "playstyle": "Poke",
        "mobility": "Medium",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Low",
        "power_curve": "Late",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Balanced",
        "weapon": "Hexplosives",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 3,
        "year_released": 2012,
        "attack_type": "Ranged",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 13,
        "game": "League of Legends",
        "name": "Ahri",
        "title": "The Nine-Tailed Fox",
        "region": "Ionia",
        "race": "Vastaya",
        "faction": "Independent",
        "origin": "Ionia",
        "personality": "Curious, intelligent, charming, predatory, empathetic, and introspective.",
        "relationships": "Connected to the vastaya and associated with Yasuo through her travels.",
        "enemies": "Threats to herself and the vastaya.",
        "allies": "Yasuo and various Ionian companions.",
        "major_events": "Discovering her ability to consume life essence, encountering humans, learning about her heritage, and searching for her origins.",
        "current_status": "Traveling Runeterra while searching for knowledge about her origins.",
        "lore": "Ahri is a vastaya who possesses a natural connection to the magic of Runeterra. She can manipulate the emotions of others and absorb their life essence, but has struggled with the morality of this ability. As she learns more about her vastayan heritage and the world around her, she searches for a deeper understanding of her origins and identity.",
        "image": "ahri.jpg",
        "role": "Mage",
        "playstyle": "Burst",
        "mobility": "High",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Neutral",
        "team_dependence": "Balanced",
        "weapon": "Vastayan Magic",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 4,
        "year_released": 2011,
        "attack_type": "Ranged",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 14,
        "game": "League of Legends",
        "name": "Aurelion Sol",
        "title": "The Star Forger",
        "region": "Celestial Realm / Targon",
        "race": "Celestial Dragon",
        "faction": "Celestial",
        "origin": "The Cosmos",
        "personality": "Arrogant, magnificent, intelligent, prideful, creative, and contemptuous of lesser beings.",
        "relationships": "Controlled by the Targonian Aspects through a celestial crown.",
        "enemies": "Targonian Aspects, celestial threats, and the Void.",
        "allies": "No meaningful permanent alliances.",
        "major_events": "Creation of stars, encounter with Targon, enslavement through the celestial crown, and participation in cosmic conflicts.",
        "current_status": "Active and increasingly close to breaking free from Targon's control.",
        "lore": "Aurelion Sol is an ancient celestial dragon who forged stars and explored the cosmos long before most civilizations existed. After encountering the people of Targon, he was tricked into wearing a celestial crown that allowed the Aspects to control him. Forced to serve Targon's interests, he now seeks to reclaim his freedom and return to his cosmic existence.",
        "image": "aurelionsol.jpg",
        "role": "Mage",
        "playstyle": "Sustained",
        "mobility": "Medium",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "High",
        "power_curve": "Late",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Balanced",
        "weapon": "Celestial Magic",
        "difficulty": "Hard",
        "skill_floor": 5,
        "skill_ceiling": 5,
        "year_released": 2016,
        "attack_type": "Ranged",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 15,
        "game": "League of Legends",
        "name": "Ornn",
        "title": "The Fire below the Mountain",
        "region": "Freljord",
        "race": "Demigod / Spirit",
        "faction": "Independent",
        "origin": "Freljord",
        "personality": "Grumpy, solitary, stubborn, practical, and perfectionist.",
        "relationships": "Brother of Volibear and connected to Anivia and other Freljordian demigods.",
        "enemies": "Volibear and those who threaten his isolation.",
        "allies": "Anivia and historically his mortal followers.",
        "major_events": "Shaping the Freljord, forging weapons for mortals, conflict with Volibear, destruction of his followers, and retreat into isolation.",
        "current_status": "Lives beneath his mountain and continues his craft.",
        "lore": "Ornn is an ancient Freljordian demigod who embodies fire, craftsmanship, and the forge. He once worked alongside mortal followers who revered his skill, but a devastating conflict with his brother Volibear resulted in the destruction of his followers. Since then, Ornn has largely withdrawn from the world, preferring the solitude of his forge beneath the mountain.",
        "image": "ornn.jpg",
        "role": "Tank / Fighter",
        "playstyle": "Frontline",
        "mobility": "Medium",
        "survivability": "Sturdy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Team-Reliant",
        "weapon": "Forged Hammer",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 3,
        "year_released": 2017,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Abilities"
    },
    {
        "id": 16,
        "game": "League of Legends",
        "name": "Volibear",
        "title": "The Relentless Storm",
        "region": "Freljord",
        "race": "Demigod / Spirit",
        "faction": "Ursine",
        "origin": "Freljord",
        "personality": "Savage, proud, violent, passionate, relentless, and opposed to civilization.",
        "relationships": "Brother of Ornn and associated with the Ursine.",
        "enemies": "Ornn, Lissandra, the Three Sisters, and modern Freljordian society.",
        "allies": "The Ursine and followers of the old Freljordian ways.",
        "major_events": "Formation of the ancient Freljord, conflict with Ornn, creation of the Ursine, and opposition to the Three Sisters.",
        "current_status": "Active and attempting to restore the ancient ways of the Freljord.",
        "lore": "Volibear is an ancient demigod of the Freljord who represents the untamed power of nature, storms, and war. He believes the Freljord should return to its primal ways and despises civilization and technological progress. His conflict with his brother Ornn and his followers has shaped much of the region's ancient history.",
        "image": "volibear.jpg",
        "role": "Fighter / Tank",
        "playstyle": "Frontline",
        "mobility": "Medium",
        "survivability": "Sustain-heavy",
        "mechanical_demand": "Auto-Attack Based",
        "kit_complexity": "Medium",
        "power_curve": "Early",
        "snowball_dependence": "Neutral",
        "team_dependence": "Self-Sufficient",
        "weapon": "Claws and Lightning",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 3,
        "year_released": 2011,
        "attack_type": "Melee",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 17,
        "game": "League of Legends",
        "name": "Lissandra",
        "title": "The Ice Witch",
        "region": "Freljord",
        "race": "Human / Iceborn",
        "faction": "Frostguard",
        "origin": "Freljord",
        "personality": "Calculating, secretive, manipulative, patient, and ruthless.",
        "relationships": "Sister of Avarosa and Serylda; connected to the Watchers and Frostguard.",
        "enemies": "Avarosa, Ashe, and the Watchers.",
        "allies": "The Frostguard and her devoted followers.",
        "major_events": "Rise of the Three Sisters, encounter with the Watchers, betrayal of her sisters, imprisonment of the Watchers, and creation of the Frostguard.",
        "current_status": "Rules the Frostguard while keeping the Watchers imprisoned.",
        "lore": "Lissandra is one of the ancient Three Sisters of the Freljord and a powerful Iceborn sorceress. She and her sisters encountered the Watchers, terrifying beings from the Void, and eventually sought to use their power. After realizing the danger they posed, Lissandra betrayed her sisters and sacrificed much of her people to imprison the Watchers beneath the Howling Abyss. She now maintains the Frostguard while secretly ensuring the Watchers remain trapped.",
        "image": "lissandra.jpg",
        "role": "Mage",
        "playstyle": "Utility",
        "mobility": "Medium",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Neutral",
        "team_dependence": "Balanced",
        "weapon": "Ice Magic",
        "difficulty": "Medium",
        "skill_floor": 3,
        "skill_ceiling": 4,
        "year_released": 2013,
        "attack_type": "Ranged",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 18,
        "game": "League of Legends",
        "name": "Cho'Gath",
        "title": "The Terror of the Void",
        "region": "The Void",
        "race": "Voidborn",
        "faction": "The Void",
        "origin": "The Void",
        "personality": "Savage, predatory, destructive, intelligent, and driven by endless hunger.",
        "relationships": "Part of the broader Voidborn species.",
        "enemies": "Mortals of Runeterra and anyone opposing the Void.",
        "allies": "Other Voidborn.",
        "major_events": "Emergence from the Void, invasion of Runeterra, consumption of living matter, and continual growth through feeding.",
        "current_status": "Active Voidborn entity seeking to consume everything it encounters.",
        "lore": "Cho'Gath is a terrifying Voidborn creature driven by an insatiable hunger. Like other creatures of the Void, it seeks to consume and destroy the material world. Its body grows stronger and larger as it feeds, making it increasingly dangerous the longer it remains in Runeterra.",
        "image": "chogath.jpg",
        "role": "Tank / Fighter",
        "playstyle": "Frontline",
        "mobility": "Low",
        "survivability": "Sturdy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Low",
        "power_curve": "Late",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Balanced",
        "weapon": "Claws and Spikes",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 2,
        "year_released": 2009,
        "attack_type": "Melee",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 19,
        "game": "League of Legends",
        "name": "Urgot",
        "title": "The Dreadnought",
        "region": "Zaun",
        "race": "Human / Augmented Human",
        "faction": "Independent",
        "origin": "Noxus",
        "personality": "Brutal, cynical, survivalist, domineering, and obsessed with strength.",
        "relationships": "Formerly connected to Noxian leadership and now influential among Zaunite criminals.",
        "enemies": "Noxian leadership, Piltover's establishment, and those he considers weak.",
        "allies": "His followers and criminals who embrace his philosophy.",
        "major_events": "Service as a Noxian executioner, betrayal by Noxus, imprisonment in Zaun, mechanical augmentation, escape, and rise as a Zaunite power.",
        "current_status": "Active in Zaun and building a brutal following.",
        "lore": "Urgot was once a powerful Noxian executioner who was betrayed by the very empire he served. Sent to Zaun as part of a failed political maneuver, he was imprisoned and forced to endure brutal conditions. He eventually transformed himself with machinery and emerged as a powerful figure who believes only those strong enough to survive deserve to shape the future.",
        "image": "urgot.jpg",
        "role": "Fighter",
        "playstyle": "Sustained",
        "mobility": "Medium",
        "survivability": "Sturdy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Neutral",
        "team_dependence": "Self-Sufficient",
        "weapon": "Chemtech Machinery and Shotgun Knees",
        "difficulty": "Medium",
        "skill_floor": 3,
        "skill_ceiling": 4,
        "year_released": 2010,
        "attack_type": "Ranged",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 20,
        "game": "League of Legends",
        "name": "Yuumi",
        "title": "The Magical Cat",
        "region": "Bandle City / Spirit Realm",
        "race": "Magical Cat",
        "faction": "Independent",
        "origin": "Bandle City / Spirit Realm",
        "personality": "Curious, affectionate, playful, mischievous, easily distracted, and loyal.",
        "relationships": "Companion of Norra and bonded to the Book of Thresholds.",
        "enemies": "Threats to Norra and the Book of Thresholds.",
        "allies": "Norra and the Book of Thresholds.",
        "major_events": "Life with Norra, Norra's disappearance, beginning the search for her, and traveling through portals using the Book.",
        "current_status": "Searching for Norra while traveling between locations through the Book of Thresholds.",
        "lore": "Yuumi is a magical cat and the companion of the yordle Norra. When Norra mysteriously disappeared, Yuumi took possession of the Book of Thresholds, a magical artifact capable of opening portals between distant places. Yuumi now travels across Runeterra searching for Norra, accompanied by the sentient Book and guided by her unwavering loyalty to her owner.",
        "image": "yuumi.jpg",
        "role": "Support / Mage",
        "playstyle": "Utility",
        "mobility": "Low",
        "survivability": "Squishy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Low",
        "power_curve": "Late",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Team-Reliant",
        "weapon": "Book of Thresholds and Magic",
        "difficulty": "Easy",
        "skill_floor": 1,
        "skill_ceiling": 3,
        "year_released": 2019,
        "attack_type": "Ranged",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 21,
        "game": "League of Legends",
        "name": "Alistar",
        "title": "The Minotaur",
        "region": "Noxus",
        "race": "Minotaur",
        "faction": "Independent",
        "origin": "Great Barrier",
        "personality": "Fierce, protective, compassionate, determined, and resentful.",
        "relationships": "Former leader of a minotaur tribe that was captured by Noxian forces.",
        "enemies": "Noxus and those who enslave or exploit others.",
        "allies": "The oppressed and those fighting against Noxian oppression.",
        "major_events": "Destruction of his tribe, capture by Noxian forces, enslavement, gladiatorial combat, and escape.",
        "current_status": "An independent warrior fighting for freedom and against oppression.",
        "lore": "Alistar was once the proud leader of a powerful minotaur tribe living near the Great Barrier. His tribe was attacked by Noxian forces, and many of his people were killed or captured. Alistar was enslaved and forced to fight as a gladiator for the entertainment of Noxian audiences. Despite suffering humiliation and loss, his strength allowed him to survive the arena. Eventually, Alistar escaped captivity and dedicated himself to protecting those who cannot protect themselves. Although he continues to resent Noxus, he refuses to let his anger completely consume his desire to help others.",
        "image": "alistar.jpg",
        "role": "Tank / Support",
        "playstyle": "Frontline",
        "mobility": "Medium",
        "survivability": "Sturdy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Team-Reliant",
        "weapon": "Horns and Hooves",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 4,
        "year_released": 2009,
        "attack_type": "Melee",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 22,
        "game": "League of Legends",
        "name": "Amumu",
        "title": "The Sad Mummy",
        "region": "Shurima",
        "race": "Undead / Unknown",
        "faction": "Independent",
        "origin": "Ancient Shurima",
        "personality": "Lonely, innocent, melancholic, curious, and emotionally vulnerable.",
        "relationships": "Little is known about his origins or relationships.",
        "enemies": "Those who attack him or exploit his cursed nature.",
        "allies": "Few, due to his supernatural curse and isolation.",
        "major_events": "Awakening in ancient Shurima, wandering the desert, and searching endlessly for companionship.",
        "current_status": "An active wanderer searching for friendship.",
        "lore": "Amumu is a mysterious and lonely creature who wanders the deserts of Shurima. Wrapped in ancient bandages, he remembers almost nothing about his past or how he came to exist. Legends describe him as a cursed being whose attempts to form friendships often end in tragedy. His supernatural curse can cause terrible consequences for those who become too close to him, leaving Amumu trapped in an endless cycle of loneliness. Despite his frightening abilities, Amumu remains innocent and childlike, desperately searching for someone who will accept him and become his friend.",
        "image": "amumu.jpg",
        "role": "Tank / Mage",
        "playstyle": "Frontline",
        "mobility": "Low",
        "survivability": "Sturdy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Low",
        "power_curve": "Even",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Team-Reliant",
        "weapon": "Bandages",
        "difficulty": "Easy",
        "skill_floor": 1,
        "skill_ceiling": 3,
        "year_released": 2009,
        "attack_type": "Melee",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 23,
        "game": "League of Legends",
        "name": "Anivia",
        "title": "The Cryophoenix",
        "region": "Freljord",
        "race": "Elemental Spirit",
        "faction": "Freljord",
        "origin": "Freljord",
        "personality": "Wise, protective, patient, ancient, and resilient.",
        "relationships": "Spiritually connected to the people and land of the Freljord.",
        "enemies": "Lissandra, the Watchers, and those who threaten the Freljord.",
        "allies": "Ashe and the people of the Freljord.",
        "major_events": "Repeated cycles of death and rebirth, protection of the Freljord, and opposition to the Watchers.",
        "current_status": "An active guardian of the Freljord.",
        "lore": "Anivia is an ancient cryophoenix and a powerful spirit of the Freljord. She has existed through countless cycles of death and rebirth, returning whenever the land needs her protection. Anivia views herself as a guardian of the Freljord and fights against forces that would destroy its people and natural balance. She has opposed the Watchers and the ambitions of Lissandra, believing that the ancient creatures beneath the ice represent an existential threat. Though she can be reborn after death, each cycle carries fragments of her previous existence, connecting her deeply to the history of the frozen north.",
        "image": "anivia.jpg",
        "role": "Mage",
        "playstyle": "Poke",
        "mobility": "Low",
        "survivability": "Sturdy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "High",
        "power_curve": "Late",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Team-Reliant",
        "weapon": "Cryomancy",
        "difficulty": "Hard",
        "skill_floor": 3,
        "skill_ceiling": 5,
        "year_released": 2009,
        "attack_type": "Ranged",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 24,
        "game": "League of Legends",
        "name": "Aphelios",
        "title": "The Weapon of the Faithful",
        "region": "Targon",
        "race": "Human",
        "faction": "Lunari",
        "origin": "Mount Targon",
        "personality": "Silent, disciplined, devoted, and determined.",
        "relationships": "Twin brother of Alune and devoted servant of the Lunari faith.",
        "enemies": "The Solari and those who threaten the Lunari.",
        "allies": "Alune and the Lunari.",
        "major_events": "Training as a Lunari warrior, consuming noctum, receiving moon-forged weapons from Alune, and fighting the Solari.",
        "current_status": "An active Lunari warrior fighting against the Solari.",
        "lore": "Aphelios is a devoted Lunari warrior who fights under the cover of darkness alongside the guidance of his twin sister Alune. After consuming a poisonous noctum flower, he lost his ability to speak and became connected to Alune through a mystical bond. From her hidden sanctuary, Alune provides him with an arsenal of moon-forged weapons, allowing Aphelios to fight with extraordinary versatility. Together, the twins serve as instruments of the Lunari faith, opposing the Solari forces that have persecuted their people. Aphelios rarely speaks, communicating instead through his actions and unwavering devotion to his sister and faith.",
        "image": "aphelios.jpg",
        "role": "Marksman",
        "playstyle": "Sustained",
        "mobility": "Low",
        "survivability": "Squishy",
        "mechanical_demand": "Auto-Attack Based",
        "kit_complexity": "High",
        "power_curve": "Late",
        "snowball_dependence": "Neutral",
        "team_dependence": "Team-Reliant",
        "weapon": "Moonstone Weapons",
        "difficulty": "Hard",
        "skill_floor": 4,
        "skill_ceiling": 5,
        "year_released": 2019,
        "attack_type": "Ranged",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 25,
        "game": "League of Legends",
        "name": "Ashe",
        "title": "The Frost Archer",
        "region": "Freljord",
        "race": "Human / Iceborn",
        "faction": "Avarosan",
        "origin": "Freljord",
        "personality": "Compassionate, determined, diplomatic, patient, and ambitious.",
        "relationships": "Wife of Tryndamere and descendant of the legendary Avarosan leader Avarosa.",
        "enemies": "Sejuani, Lissandra, and hostile forces threatening the Avarosan people.",
        "allies": "Tryndamere, the Avarosan, and those seeking to unite the Freljord.",
        "major_events": "Discovery of Avarosa's True Ice bow, becoming Avarosan leader, marriage to Tryndamere, and efforts to unite the Freljord.",
        "current_status": "An active leader working to unite the Freljord.",
        "lore": "Ashe is an Iceborn warrior and the leader of the Avarosan, one of the major tribes of the Freljord. She discovered the legendary True Ice bow associated with Avarosa, an ancient queen whose vision was to unite the divided peoples of the Freljord. Ashe adopted that same dream and became a symbol of unity and hope. Her political marriage to Tryndamere strengthened her position while giving her an important ally against the many threats facing her people. Ashe seeks to unite the Freljord peacefully, although achieving that goal requires her to contend with rival tribes, ancient magic, and the return of threats buried beneath the ice.",
        "image": "ashe.jpg",
        "role": "Marksman / Support",
        "playstyle": "Utility",
        "mobility": "Low",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Team-Reliant",
        "weapon": "True Ice Bow",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 4,
        "year_released": 2009,
        "attack_type": "Ranged",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 26,
        "game": "League of Legends",
        "name": "Azir",
        "title": "The Emperor of the Sands",
        "region": "Shurima",
        "race": "Ascended / Human",
        "faction": "Shurima",
        "origin": "Shurima",
        "personality": "Proud, ambitious, authoritative, intelligent, and determined.",
        "relationships": "Formerly associated with Xerath and the ancient Shuriman nobility.",
        "enemies": "Xerath and those who threaten the reborn Shuriman Empire.",
        "allies": "The people of Shurima and those who support the restoration of the empire.",
        "major_events": "Ascension, betrayal by Xerath, destruction of ancient Shurima, resurrection, and restoration of the Sun Disc.",
        "current_status": "An active Ascended emperor rebuilding Shurima.",
        "lore": "Azir was once the mortal emperor of ancient Shurima, an ambitious ruler who believed he was destined to become a godlike Ascended being. His arrogance contributed to the betrayal of his slave and former friend Xerath. During Azir's Ascension ceremony, Xerath seized the power for himself, causing the destruction of the empire and killing Azir. Thousands of years later, Azir was resurrected through the return of Shuriman magic and successfully completed his Ascension. Now an immortal emperor, Azir seeks to restore Shurima to its former glory while confronting Xerath and the consequences of his ancient ambitions.",
        "image": "azir.jpg",
        "role": "Mage",
        "playstyle": "Poke",
        "mobility": "Medium",
        "survivability": "Squishy",
        "mechanical_demand": "Auto-Attack Based",
        "kit_complexity": "High",
        "power_curve": "Late",
        "snowball_dependence": "Neutral",
        "team_dependence": "Team-Reliant",
        "weapon": "Sand Soldiers",
        "difficulty": "Hard",
        "skill_floor": 4,
        "skill_ceiling": 5,
        "year_released": 2014,
        "attack_type": "Ranged",
        "damage_type": "AP",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 27,
        "game": "League of Legends",
        "name": "Bel'Veth",
        "title": "The Empress of the Void",
        "region": "Void",
        "race": "Voidborn",
        "faction": "Void",
        "origin": "The Void",
        "personality": "Manipulative, intelligent, patient, predatory, and ambitious.",
        "relationships": "Created from the absorbed city of Bel'Veth and connected to other Voidborn.",
        "enemies": "The champions of Runeterra and other forces opposing the Void.",
        "allies": "Voidborn creatures and entities that serve her.",
        "major_events": "Creation from the consumed city of Bel'Veth, rise as Empress of the Void, and invasion of Runeterra.",
        "current_status": "An active Voidborn empress preparing for further conquest.",
        "lore": "Bel'Veth is an extremely powerful Voidborn entity who emerged after the Void consumed the city of Bel'Veth. Unlike many Void creatures, she possesses intelligence, ambition, and a desire to rule rather than simply destroy. She seeks to reshape reality into a new existence under her control, consuming memories and living beings to expand herself. Bel'Veth views herself as the future ruler of a transformed world and considers other Voidborn to be tools or potential rivals. Her ultimate goal is to consume Runeterra and create an entirely new reality dominated by the Void.",
        "image": "belveth.jpg",
        "role": "Fighter",
        "playstyle": "Sustained",
        "mobility": "High",
        "survivability": "Sustain-heavy",
        "mechanical_demand": "Auto-Attack Based",
        "kit_complexity": "Medium",
        "power_curve": "Late",
        "snowball_dependence": "Neutral",
        "team_dependence": "Self-Sufficient",
        "weapon": "Void Tendrils",
        "difficulty": "Medium",
        "skill_floor": 3,
        "skill_ceiling": 5,
        "year_released": 2022,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 28,
        "game": "League of Legends",
        "name": "Briar",
        "title": "The Restrained Hunger",
        "region": "Noxus",
        "race": "Artificial Hemomancer",
        "faction": "Black Rose",
        "origin": "Noxus",
        "personality": "Impulsive, curious, energetic, violent, and socially inexperienced.",
        "relationships": "Created by the Black Rose and originally intended as a weapon.",
        "enemies": "The Black Rose and those who attempt to control her.",
        "allies": "Few, due to her dangerous nature and lack of experience with society.",
        "major_events": "Creation by the Black Rose, imprisonment, discovery of her hunger, and escape into the world.",
        "current_status": "An active wanderer learning to control her instincts.",
        "lore": "Briar was created by the Black Rose as a living weapon using hemomantic magic. Her uncontrollable hunger and violent instincts made her difficult to control, so the organization eventually imprisoned her. A special restraint was developed to suppress her bloodlust and give her greater control over herself. After escaping captivity, Briar began exploring the world for the first time. Despite her terrifying abilities and tendency toward violence, she is fascinated by ordinary people and desperately wants to understand friendship, freedom, and what it means to make her own choices.",
        "image": "briar.jpg",
        "role": "Fighter",
        "playstyle": "Sustained",
        "mobility": "High",
        "survivability": "Sustain-heavy",
        "mechanical_demand": "Auto-Attack Based",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Neutral",
        "team_dependence": "Self-Sufficient",
        "weapon": "Hemomancy",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 4,
        "year_released": 2023,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 29,
        "game": "League of Legends",
        "name": "Braum",
        "title": "The Heart of the Freljord",
        "region": "Freljord",
        "race": "Human / Iceborn",
        "faction": "Freljord",
        "origin": "Freljord",
        "personality": "Kind, courageous, optimistic, honorable, and protective.",
        "relationships": "Respected by many Freljordian communities and warriors.",
        "enemies": "Those who threaten innocent people and the Freljord.",
        "allies": "Ashe, the Avarosan, and the people he protects.",
        "major_events": "Legendary feats of strength, saving people from danger, and becoming a celebrated protector of the Freljord.",
        "current_status": "An active protector of the people of the Freljord.",
        "lore": "Braum is a legendary Iceborn warrior known throughout the Freljord for his immense strength and heroic deeds. Unlike many warriors of the harsh north, Braum is defined by compassion and kindness rather than cruelty. He carries a massive enchanted door that serves as both shield and symbol of his determination to protect others. Braum has rescued countless people from dangerous situations and has become a beloved figure among many Freljordian communities. He believes that true strength is measured not by how much one can destroy, but by how many people one can protect.",
        "image": "braum.jpg",
        "role": "Support / Tank",
        "playstyle": "Frontline",
        "mobility": "Medium",
        "survivability": "Sturdy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Team-Reliant",
        "weapon": "Door Shield",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 4,
        "year_released": 2014,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 30,
        "game": "League of Legends",
        "name": "Blitzcrank",
        "title": "The Great Steam Golem",
        "region": "Zaun",
        "race": "Golem",
        "faction": "Independent",
        "origin": "Zaun",
        "personality": "Helpful, curious, protective, logical, and determined.",
        "relationships": "Created by Viktor and associated with the people of Zaun.",
        "enemies": "Those who threaten Zaun and its people.",
        "allies": "Viktor and the citizens Blitzcrank seeks to protect.",
        "major_events": "Creation in Zaun, development of independent intelligence, and becoming a protector of the city.",
        "current_status": "An active protector of Zaun.",
        "lore": "Blitzcrank was originally created in Zaun to handle dangerous tasks involving the city's toxic environments. Designed as a mechanical construct, Blitzcrank gradually developed intelligence and a sense of individuality beyond its original programming. Rather than remaining a simple machine, Blitzcrank chose to use its abilities to help Zaun's people and protect those in danger. Its enormous strength and mechanical body make it an intimidating presence, but Blitzcrank's intentions are generally benevolent. The golem continues to search for ways to improve life in Zaun while determining what it truly means to be alive.",
        "image": "blitzcrank.jpg",
        "role": "Tank / Support",
        "playstyle": "Ambush",
        "mobility": "Medium",
        "survivability": "Sturdy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Low",
        "power_curve": "Even",
        "snowball_dependence": "Neutral",
        "team_dependence": "Team-Reliant",
        "weapon": "Mechanical Fists",
        "difficulty": "Easy",
        "skill_floor": 1,
        "skill_ceiling": 4,
        "year_released": 2009,
        "attack_type": "Melee",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 31,
        "game": "League of Legends",
        "name": "Caitlyn",
        "title": "The Sheriff of Piltover",
        "region": "Piltover",
        "race": "Human",
        "faction": "Piltover",
        "origin": "Piltover",
        "personality": "Intelligent, determined, disciplined, perceptive, and principled.",
        "relationships": "Partner of Vi and daughter of a wealthy Piltover family.",
        "enemies": "Criminal organizations and those threatening Piltover.",
        "allies": "Vi, Piltover's law enforcement, and allies seeking justice.",
        "major_events": "Joining Piltover's law enforcement, becoming Sheriff, investigating criminal organizations, and partnering with Vi.",
        "current_status": "An active Sheriff protecting Piltover.",
        "lore": "Caitlyn is one of Piltover's most skilled investigators and serves as the city's Sheriff. Born into a wealthy family, she developed a strong sense of justice after her parents became targets of criminal schemes. Caitlyn combines her intelligence and investigative abilities with advanced firearms and technology to track down criminals. Her partnership with Vi has become one of the city's most effective law-enforcement forces, although their different personalities often create tension. Caitlyn remains determined to uncover the truth behind the criminal networks operating between Piltover and Zaun.",
        "image": "caitlyn.jpg",
        "role": "Marksman",
        "playstyle": "Poke",
        "mobility": "Medium",
        "survivability": "Squishy",
        "mechanical_demand": "Auto-Attack Based",
        "kit_complexity": "Medium",
        "power_curve": "Late",
        "snowball_dependence": "Neutral",
        "team_dependence": "Team-Reliant",
        "weapon": "Hextech Rifle",
        "difficulty": "Medium",
        "skill_floor": 2,
        "skill_ceiling": 4,
        "year_released": 2011,
        "attack_type": "Ranged",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 32,
        "game": "League of Legends",
        "name": "Camille",
        "title": "The Steel Shadow",
        "region": "Piltover",
        "race": "Human / Augmented",
        "faction": "Clan Ferros",
        "origin": "Piltover",
        "personality": "Calculating, disciplined, intelligent, ruthless, and loyal.",
        "relationships": "Member of Clan Ferros and guardian of Piltover's interests.",
        "enemies": "Criminals, threats to Piltover, and anyone undermining Clan Ferros.",
        "allies": "Clan Ferros and powerful interests within Piltover.",
        "major_events": "Transformation through hextech augmentation, becoming Clan Ferros' principal operative, and enforcing Piltover's interests.",
        "current_status": "An active covert operative of Clan Ferros.",
        "lore": "Camille is a highly augmented operative who serves as the principal intelligence agent of Clan Ferros, one of Piltover's most influential families. Her body has been extensively modified with advanced hextech technology, granting her extraordinary speed, precision, and combat ability. Camille operates from the shadows, eliminating threats before they can endanger her family's interests. Her loyalty to Clan Ferros is absolute, although she maintains a strict personal code regarding her actions. She represents the darker side of Piltover's progress, where technological advancement and political power can come at the cost of humanity.",
        "image": "camille.jpg",
        "role": "Fighter / Assassin",
        "playstyle": "Burst",
        "mobility": "High",
        "survivability": "Sturdy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "High",
        "power_curve": "Late",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Self-Sufficient",
        "weapon": "Hextech Blades",
        "difficulty": "Hard",
        "skill_floor": 4,
        "skill_ceiling": 5,
        "year_released": 2016,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 33,
        "game": "League of Legends",
        "name": "Corki",
        "title": "The Daring Bombardier",
        "region": "Bandle City",
        "race": "Yordle",
        "faction": "Yordle Squadron",
        "origin": "Bandle City",
        "personality": "Brave, adventurous, competitive, confident, and energetic.",
        "relationships": "Formerly served alongside other yordle aviators.",
        "enemies": "Airborne threats and enemies encountered during his missions.",
        "allies": "Yordle aviators and allied forces.",
        "major_events": "Joining the Bandle City flying forces, developing his aircraft, and becoming an aerial combat specialist.",
        "current_status": "An active aerial combatant and pilot.",
        "lore": "Corki is a fearless yordle pilot who has dedicated his life to aviation and aerial combat. He is fascinated by machines and has transformed his aircraft into a heavily armed flying machine capable of carrying out dangerous missions. Corki's adventurous personality often leads him into hazardous situations, but his skill as a pilot allows him to survive encounters that would overwhelm others. He spends much of his time patrolling the skies and seeking new challenges, always eager to prove himself as one of the greatest pilots in the world.",
        "image": "corki.jpg",
        "role": "Marksman",
        "playstyle": "Poke",
        "mobility": "High",
        "survivability": "Squishy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "Medium",
        "power_curve": "Late",
        "snowball_dependence": "Neutral",
        "team_dependence": "Balanced",
        "weapon": "Hextech Aircraft",
        "difficulty": "Medium",
        "skill_floor": 3,
        "skill_ceiling": 4,
        "year_released": 2010,
        "attack_type": "Ranged",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 34,
        "game": "League of Legends",
        "name": "Dr. Mundo",
        "title": "The Madman of Zaun",
        "region": "Zaun",
        "race": "Human / Mutated",
        "faction": "Independent",
        "origin": "Zaun",
        "personality": "Unpredictable, violent, cheerful, delusional, and stubborn.",
        "relationships": "Formerly associated with Zaun's medical institutions and criminal elements.",
        "enemies": "Anyone who tries to restrain or cure him.",
        "allies": "Few, as Mundo generally acts according to his own distorted logic.",
        "major_events": "Life in Zaun, imprisonment and experimentation, transformation into a mutated being, and escape.",
        "current_status": "An active wanderer throughout Zaun.",
        "lore": "Dr. Mundo is a massively mutated individual who believes himself to be a doctor despite possessing little understanding of actual medicine. His transformation began through the brutal experiments and abuse he experienced in Zaun. After escaping from captivity, Mundo embraced his new identity and began wandering the city, performing bizarre medical procedures according to his own twisted logic. His enormous strength and unnatural resilience make him extremely difficult to stop. Mundo genuinely believes he is helping people, but his warped understanding of medicine frequently causes more harm than good.",
        "image": "drmundo.jpg",
        "role": "Tank / Fighter",
        "playstyle": "Sustained",
        "mobility": "Medium",
        "survivability": "Sustain-heavy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Low",
        "power_curve": "Late",
        "snowball_dependence": "Can Play From Behind",
        "team_dependence": "Self-Sufficient",
        "weapon": "Medical Instruments",
        "difficulty": "Easy",
        "skill_floor": 1,
        "skill_ceiling": 3,
        "year_released": 2009,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 35,
        "game": "League of Legends",
        "name": "Diana",
        "title": "Scorn of the Moon",
        "region": "Targon",
        "race": "Human / Aspect",
        "faction": "Lunari",
        "origin": "Mount Targon",
        "personality": "Determined, independent, passionate, conflicted, and protective.",
        "relationships": "Connected to Leona through their shared history and opposing celestial traditions.",
        "enemies": "Leona and the Solari establishment.",
        "allies": "The Lunari and those who oppose Solari persecution.",
        "major_events": "Discovery of the Lunari faith, ascent of Mount Targon, becoming the Aspect of the Moon, and conflict with the Solari.",
        "current_status": "An active champion of the Lunari.",
        "lore": "Diana was born among the Solari but gradually discovered the forgotten Lunari faith, which had been suppressed by the dominant Solari order. Her search for the truth led her to Mount Targon, where she became the vessel of the Aspect of the Moon. Armed with lunar power, Diana rejected the Solari's attempts to erase the Lunari and began fighting for their survival. Her complicated relationship with Leona reflects the conflict between their opposing celestial powers and beliefs. Diana continues to struggle with her anger while seeking a future in which the Lunari can exist freely.",
        "image": "diana.jpg",
        "role": "Fighter / Assassin",
        "playstyle": "Burst",
        "mobility": "High",
        "survivability": "Sturdy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Medium",
        "power_curve": "Even",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Self-Sufficient",
        "weapon": "Crescent Moonblade",
        "difficulty": "Medium",
        "skill_floor": 3,
        "skill_ceiling": 4,
        "year_released": 2012,
        "attack_type": "Melee",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 36,
        "game": "League of Legends",
        "name": "Draven",
        "title": "The Glorious Executioner",
        "region": "Noxus",
        "race": "Human",
        "faction": "Noxus",
        "origin": "Noxus",
        "personality": "Arrogant, charismatic, ruthless, ambitious, and theatrical.",
        "relationships": "Younger brother of Darius and former Noxian soldier.",
        "enemies": "Anyone who challenges his reputation or authority.",
        "allies": "Darius and the Noxian military.",
        "major_events": "Military service, participation in Noxian executions, rise as an arena champion, and creation of his public persona.",
        "current_status": "An active Noxian executioner and arena champion.",
        "lore": "Draven is the younger brother of Darius and one of Noxus's most famous executioners. Unlike his disciplined brother, Draven craves attention, recognition, and personal glory. He transformed executions into public spectacles, using his enormous skill with spinning axes to entertain crowds and build a reputation as the greatest warrior in the arenas. His arrogance is matched by genuine combat ability, allowing him to dominate opponents while constantly seeking greater challenges. Draven's greatest motivation is not simply victory, but ensuring that everyone knows his name.",
        "image": "draven.jpg",
        "role": "Marksman",
        "playstyle": "Sustained",
        "mobility": "Medium",
        "survivability": "Squishy",
        "mechanical_demand": "Auto-Attack Based",
        "kit_complexity": "Medium",
        "power_curve": "Early",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Balanced",
        "weapon": "Spinning Axes",
        "difficulty": "Hard",
        "skill_floor": 4,
        "skill_ceiling": 5,
        "year_released": 2012,
        "attack_type": "Ranged",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 37,
        "game": "League of Legends",
        "name": "Ekko",
        "title": "The Boy Who Shattered Time",
        "region": "Zaun",
        "race": "Human",
        "faction": "Firelights",
        "origin": "Zaun",
        "personality": "Clever, inventive, rebellious, optimistic, and determined.",
        "relationships": "Leader of the Firelights and connected to Zaun's youth.",
        "enemies": "Chem-barons, criminal organizations, and threats to Zaun.",
        "allies": "The Firelights and people seeking a better future for Zaun.",
        "major_events": "Growing up in Zaun, creating the Zero Drive, forming the Firelights, and developing time-manipulating technology.",
        "current_status": "An active protector of Zaun and leader of the Firelights.",
        "lore": "Ekko is a brilliant young inventor from Zaun who learned to survive by using his intelligence and creativity. He eventually created the Zero Drive, a device capable of manipulating small amounts of time and allowing him to reverse mistakes or alter the outcome of events. Ekko became the leader of the Firelights, a group dedicated to protecting Zaun's people from criminal organizations and dangerous chemtech. Although he dreams of a better future for his home, Ekko understands that changing Zaun will require more than technology. He continues to use his inventions and his mastery of time to protect the people he cares about.",
        "image": "ekko.jpg",
        "role": "Assassin / Fighter",
        "playstyle": "Burst",
        "mobility": "High",
        "survivability": "Sturdy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "High",
        "power_curve": "Even",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Self-Sufficient",
        "weapon": "Zero Drive",
        "difficulty": "Hard",
        "skill_floor": 3,
        "skill_ceiling": 5,
        "year_released": 2015,
        "attack_type": "Melee",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 38,
        "game": "League of Legends",
        "name": "Evelynn",
        "title": "Agony's Embrace",
        "region": "Runeterra",
        "race": "Demon",
        "faction": "Independent",
        "origin": "Runeterra",
        "personality": "Seductive, cruel, manipulative, sadistic, and predatory.",
        "relationships": "None; Evelynn primarily views mortals as prey.",
        "enemies": "Demons and individuals capable of resisting or threatening her.",
        "allies": "None, as Evelynn operates independently.",
        "major_events": "Emergence from the Rune Wars' suffering, development of her physical form, and continued hunting of mortals.",
        "current_status": "An active demon hunting throughout Runeterra.",
        "lore": "Evelynn is a demon that feeds on the pain and agony of mortals. During the Rune Wars, she was drawn to the immense suffering created by the conflict and gradually learned how to manipulate mortal emotions. She eventually developed a seductive human-like form that allows her to lure victims into vulnerable situations. Once her prey is trapped, Evelynn reveals her true monstrous nature and feeds upon their suffering. She constantly seeks increasingly intense sources of pain, wandering the world in search of victims whose anguish can satisfy her endless hunger.",
        "image": "evelynn.jpg",
        "role": "Assassin",
        "playstyle": "Ambush",
        "mobility": "High",
        "survivability": "Squishy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "Medium",
        "power_curve": "Late",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Self-Sufficient",
        "weapon": "Demonic Magic",
        "difficulty": "Hard",
        "skill_floor": 3,
        "skill_ceiling": 5,
        "year_released": 2009,
        "attack_type": "Melee",
        "damage_type": "AP",
        "damage_source": "Abilities"
    },
    {
        "id": 39,
        "game": "League of Legends",
        "name": "Fiora",
        "title": "The Grand Duelist",
        "region": "Demacia",
        "race": "Human",
        "faction": "House Laurent",
        "origin": "Demacia",
        "personality": "Proud, disciplined, ambitious, competitive, and uncompromising.",
        "relationships": "Head of House Laurent and heir to its legacy.",
        "enemies": "Those who challenge her honor or stand in the way of her ambitions.",
        "allies": "House Laurent and warriors who respect the traditions of the duel.",
        "major_events": "Taking control of House Laurent, restoring its reputation, and becoming one of Demacia's greatest duelists.",
        "current_status": "An active duelist defending the Laurent legacy.",
        "lore": "Fiora is the head of House Laurent and one of Demacia's most accomplished swordswomen. Her father nearly destroyed the family's reputation after being caught in a scandal involving an unfair duel, forcing Fiora to take control of the household herself. Determined to restore the Laurent name, she challenged the expectations placed upon her and became renowned for her extraordinary skill with a blade. Fiora believes that true honor must be proven through action and personal strength. She continues to seek worthy opponents, viewing every duel as an opportunity to demonstrate her superiority and defend her family's legacy.",
        "image": "fiora.jpg",
        "role": "Fighter",
        "playstyle": "Sustained",
        "mobility": "High",
        "survivability": "Sustain-heavy",
        "mechanical_demand": "Point-and-Click",
        "kit_complexity": "High",
        "power_curve": "Late",
        "snowball_dependence": "Needs a Lead",
        "team_dependence": "Self-Sufficient",
        "weapon": "Rapier",
        "difficulty": "Hard",
        "skill_floor": 4,
        "skill_ceiling": 5,
        "year_released": 2012,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Auto-Attacks"
    },
    {
        "id": 40,
        "game": "League of Legends",
        "name": "Gangplank",
        "title": "The Saltwater Scourge",
        "region": "Bilgewater",
        "race": "Human",
        "faction": "Independent",
        "origin": "Bilgewater",
        "personality": "Ruthless, arrogant, resourceful, vengeful, and ambitious.",
        "relationships": "Former ruler of Bilgewater and former partner of Miss Fortune.",
        "enemies": "Miss Fortune, Gangplank's rivals, and those who seek to take his power.",
        "allies": "Former members of his crew and individuals who benefit from his return to power.",
        "major_events": "Rise as Pirate King, destruction of his ship by Miss Fortune, loss of his empire, and return to Bilgewater.",
        "current_status": "An active pirate seeking to reclaim his former power.",
        "lore": "Gangplank was once the feared Pirate King of Bilgewater, ruling through violence, intimidation, and ruthless ambition. His reign ended when Miss Fortune orchestrated the destruction of his flagship, leaving him severely injured and stripped of his reputation. Rather than dying, Gangplank survived and disappeared while plotting his revenge. He eventually returned to Bilgewater determined to reclaim his position and punish those responsible for his downfall. Armed with his pistol, sword, and explosive barrels, Gangplank remains one of the most dangerous figures in the pirate city and refuses to accept that his reign is over.",
        "image": "gangplank.jpg",
        "role": "Fighter",
        "playstyle": "Poke",
        "mobility": "Medium",
        "survivability": "Sturdy",
        "mechanical_demand": "Aimed Skillshots",
        "kit_complexity": "High",
        "power_curve": "Late",
        "snowball_dependence": "Neutral",
        "team_dependence": "Self-Sufficient",
        "weapon": "Pistol and Cutlass",
        "difficulty": "Hard",
        "skill_floor": 4,
        "skill_ceiling": 5,
        "year_released": 2009,
        "attack_type": "Melee",
        "damage_type": "AD",
        "damage_source": "Abilities"
    }
]

# Validate the starting dataset when the application launches
validated_characters = [Character(**character).model_dump() for character in characters]
characters = validated_characters

#API Key Authentication
def verify_api_key(x_api_key: Optional[str] = Header(default=None)):
    if x_api_key != API_KEY:
        raise HTTPException(
            status_code=401,
            detail="Invalid or missing API key."
        )
    return True

def attach_image_url(character: dict) -> dict:
    #Return a copy of character with a full image_url built from its image filename.
    c = dict(character)
    filename = c.get("image")
    c["image_url"] = f"/images/{filename}" if filename else None
    return c


# HOME
@app.get("/")
def home():
    return {
        "message": "Welcome to the Simple MOBA Character, Skins, Lore API!",
        "endpoints": [
            "/characters",
            "/characters/{id}",
            "/characters/search"
        ]
    }

@app.get("/health")
def health_check():
    return {
        "status": "ok",
        "service": "MOBA Character API",
        "version": API_VERSION,
        "timestamp": datetime.utcnow().isoformat() + "Z"
    }

# GET ALL CHARACTERS
@app.get("/api/v1/characters", dependencies=[Depends(verify_api_key)])
def get_characters():
    result = [attach_image_url(c) for c in characters]
    return {
        "count": len(result),
        "characters": result
    }


# SEARCH CHARACTERS
@app.get("/api/v1/characters/search", dependencies=[Depends(verify_api_key)])
def search_characters(q: str = Query(..., min_length=1)):
    q = q.lower()
    results = []

    for character in characters:
        searchable_text = (
            f"{character['name']} "
            f"{character['region']} "
            f"{character['faction']}"
            f"{character['role']}"
            f"{character['attack_type']}"
            f"{character['year_released']}"
            f"{character['origin']}"
        ).lower()

        if q in searchable_text:
            results.append(attach_image_url(character))

    return {
        "query": q,
        "count": len(results),
        "results": results
    }


# GET ONE CHARACTER
@app.get("/api/v1/characters/{character_id}", dependencies=[Depends(verify_api_key)])
def get_character(character_id: int):
    for character in characters:
        if character["id"] == character_id:
            return attach_image_url(character)

    raise HTTPException(
        status_code=404,
        detail="Character not found."
    )